### ISSUE TITLE
Explicitar CLI no README.md

### ISSUE THREAD

**Issue by danielmitre** [joseims/doqueru-kun#14]
A CLI está até que bem descrita no doqueru.cpp, na função **config**, mas seria interessante descrever melhor no README.md

**Comment by alexsantee** [comment]
Mandei um pull request com transcrição simples do que tinha na função config do doqueru.cpp.

 É mais ou menos isso que vocês têm em mente (em termos de conteúdo, sintaxe e afins)?

Qualquer coisa que esteja errada ou faltando estou disposto a corrigir!

**Comment by danielmitre** [comment]
Acho que ficaria melhor se o título fosse "Usage" em vez de "opções da cli". Aí dava a sintaxe de uso (./doqueru [OPTIONS]) e descreveria as opções logo abaixo como você já fez.

O que tenho na minha cabeça é a saída de um **ls --help** na verdade, mas se você tiver como referência algum README legal de um repositório relevante (ou da sua cabeça mesmo), sinta-se livre para mimetizá-lo.

**Comment by alexsantee** [comment]
Terminei as modificações sugeridas!
Fiz o possível para parecer com uma página de manual do linux. Era essa a idea?

**Comment by danielmitre** [comment]
Era isso mesmo, obrigado!
