### ISSUE TITLE
Fix github language detection

### ISSUE THREAD

**Issue by danielmitre** [joseims/doqueru-kun#20]
We just have written C, but the GitHub also scanned the code of the Alphine image.

Anyone have some idea of how to stop the image from being scanned for language detection?

**Comment by danielmitre** [comment]
The alternative can be also a way of download and extract the image automatically.

It is possible to hide some directory tree into a single file? It would be a nice way of saving the state of a container and the image itself.

**Comment by fanny** [comment]
Hi @danielmitre, i can solve this. GitHub has a [linguist library](https://github.com/github/linguist) that auto-detects the language within every repository. The documentation saids that is enough  add just one line to a `.gitattributes` file for resolve the language issues.
So, you can assign for me?

**Comment by danielmitre** [comment]
That's very nice, assigned!
